### ISSUE TITLE
Add debug and stop/start record number for debugging on dirty data

### ISSUE THREAD

**Issue by antaenc** [Senzing/mapper-csv#15]
The following would be useful for debugging when working on dirty data and/or data with spurious non-printable chars:

- Debug argument to print line number and row being processed. This is useful to see issues in the inbound record and know the line number for replacing/deleting/etc with something like sed. 

- Skip x records and stop on y record. When working on a large file with multiple issues in the data in it can skip over to the approximate area of the error and also stop after x number. This would also be useful for creating smaller test sets to work with before a full load. G2Loader has these, model from there.

**Comment by jbutcher21** [comment]
It already reports the line number it errors on.  Easier to just grep it out than to add code.
